### PR TITLE
Updating Preview

### PR DESCRIPTION
**Pull request by Pukimaa**
1. Using Pomelo (new username system)
2. Added tooltips

### CODE REVIEW

**Comment by vaporvee** [comment]
Can you make the contrast for the tooltips higher? Or should we leave that original?

**Comment by vaporvee** [comment]
also shouldn't they overlap with "Playing a game"?

**Comment by vaporvee** [comment]
overlapping shows that its nothing that will be constant visible thats also my issue with the contrast

**Comment by vaporvee** [comment]
also that would be more like the orignal screenshot

**Comment by vaporvee** [comment]
perfect could you quickly squash the commits?

**Comment by Pukimaa** [comment]
> perfect could you quickly squash the commits?

Done!

**Review by vaporvee — APPROVED** [review]
lgtm

**Pull request merged**
