### PR TITLE
macOS sucks

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
Just make sure you create a `GITHUB_TOKEN` secret in the repo settings and you're good to go. Have fun getting something from my Steam Wishlist for Chistmas <3

### CODE REVIEW

**Comment by vaporvee** [comment]
where do i get the token lol

**Comment by vaporvee** [comment]
And please change the message to:
"MacOS cant be supported because we would have to pay for a developer license to correctly compile its binaries.
You are welcome to compile them yourself because they would work!"

**Comment by koyuawsmbrtn** [comment]
> where do i get the token lol

https://github.com/settings/tokens



> And please change the message to:
> "MacOS cant be supported because we would have to pay for a developer license to correctly compile its binaries.
> You are welcome to compile them yourself because they would work!"

I'd rather say "macOS cant be supported, because loading libraries in Godot from third-party sources requires a paid developer certificate from Apple. You are welcome to compile and sign the library yourself."

Sounds a bit more professional

**Comment by vaporvee** [comment]
Then change you commit

**Comment by koyuawsmbrtn** [comment]
Done

**Pull request merged**
